service: electron-calc-api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: dev
  
functions:
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: post
          cors: true
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: true
  saveData:
    handler: handler.saveData
    events:
      - http:
          path: data
          method: post
          cors: true
  loadAllData:
    handler: handler.loadAllData
    events:
      - http:
          path: datas/{user}
          method: get
          cors: true
  loadData:
    handler: handler.loadData
    events:
      - http:
          path: data/{id}
          method: get
          cors: true

plugins:
  - serverless-offline
